services:
  - type: web
    name: code-agent
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn code_agent:app --host 0.0.0.0 --port 10000
    envVars:
      - key: OPENROUTER_API_KEY
        value: your-real-openrouter-key-here
